try to handle running build on label

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,8 +1,52 @@
 name: Continuous Integration
 
-on: push
+on:
+  push:
+  pull_request:
+    types: [ labeled ]
 jobs:
+  prepare:
+    runs-on: ubuntu-latest
+    outputs:
+      uuid: ${{ steps.uuid.outputs.value }}
+      pr_labels: ${{ steps.pr.outputs.labels }}
+      run_regression: ${{ steps.run_regression.outputs.value }}
+    permissions:
+      pull-requests: read
+    steps:
+      - name: Bail if not a push or run regression label
+        if: github.event_name == 'push' || (github.event.action == 'labeled' && github.event.label.name == 'run regression')
+        # note we might want to use an ::error or ::notice message to improve this behavior
+        # https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-error-message
+        run: exit 1
+      - uses: actions/checkout@v4
+      - name: Get PR labels
+        id: pr
+        # the github.event.pull_request.labels is not available when a build
+        # is triggered by a push. So we use the `gh` CLI to get info about the PR for the
+        # current branch.
+        # - If the branch doesn't have a PR yet, then the `gh pr view` command fails with
+        # the message: no pull requests found for branch "pr-label-test"
+        # - If the same branch is part of multiple PR, it isn't clear what will
+        # will happen, but that should be very unusual.
+        run: echo "labels=$(gh pr view --json labels -q '.labels' || echo "[]")" >> $GITHUB_OUTPUT
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      - name: Print PR labels
+        run: echo "PR labels ${{ steps.pr.outputs.labels }}"
+      - name: Get run_regression
+        id: run_regression
+        run: echo "value=${{ contains(fromJSON(steps.pr.outputs.labels).*.name, 'run regression') }}"
+      - name: Generate unique ID 💎
+        id: uuid
+        # take the current commit + timestamp together
+        # the typical value would be something like
+        # "sha-5d3fe...35d3-time-1620841214"
+        run: echo "value=sha-$GITHUB_SHA-time-$(date +"%s")" >> $GITHUB_OUTPUT
+      - name: Print unique ID
+        run: echo "generated id ${{ steps.uuid.outputs.value }}"
   build_test:
+    needs: ['prepare']
     name: Build and Run Jest Tests
     runs-on: ubuntu-latest
     steps:
@@ -24,34 +68,6 @@ jobs:
         with:
           flags: jest
           token: ${{ secrets.CODECOV_TOKEN }}
-  prepare:
-    runs-on: ubuntu-latest
-    outputs:
-      uuid: ${{ steps.uuid.outputs.value }}
-      pr_labels: ${{ steps.pr.outputs.labels }}
-    permissions:
-      pull-requests: read
-    steps:
-      - uses: actions/checkout@v4
-      - name: Get PR labels
-        id: pr
-        # the github.event.pull_request.labels is not available when a build
-        # is triggered by a push. So we use the `gh` CLI to get info about the PR for the
-        # current branch. If the same branch is part of multiple PR or the branch doesn't
-        # have a PR, I'm not sure what will happen yet.
-        run: echo "labels=$(gh pr view --json labels -q '.labels' || echo "[]")" >> $GITHUB_OUTPUT
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      - name: Print PR labels
-        run: echo "PR labels ${{ steps.pr.outputs.labels }}"
-      - name: Generate unique ID 💎
-        id: uuid
-        # take the current commit + timestamp together
-        # the typical value would be something like
-        # "sha-5d3fe...35d3-time-1620841214"
-        run: echo "value=sha-$GITHUB_SHA-time-$(date +"%s")" >> $GITHUB_OUTPUT
-      - name: Print unique ID
-        run: echo "generated id ${{ steps.uuid.outputs.value }}"
   cypress:
     needs: ['prepare']
     runs-on: ubuntu-latest
@@ -143,13 +159,11 @@ jobs:
           topBranches: |
             ["master"]
   regression:
+    needs: ['prepare']
     # only run the regression tests if the PR is labeled.
-    # I'm not sure if this approach will work for a json output
-    if: contains(fromJSON(needs.prepare.outputs.pr_labels).*.name, 'run regression')
+    if: fromJSON(needs.prepare.outputs.run_regression)
     runs-on: ubuntu-latest
     timeout-minutes: 240
-    needs:
-      - prepare
     container: cypress/browsers:node16.14.2-slim-chrome103-ff102
     strategy:
       # when one test fails, DO NOT cancel the other
